from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import joblib
import pandas as pd
import numpy as np
import shap
import json  # Added to read the metrics file

app = FastAPI(title="SecureEther API")

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- CONFIG ---
MODEL_DIR = "../models/"
DATA_PATH = "../data/transaction_dataset.csv"

# Load Models & Data Globally
try:
    print("⏳ Loading Models & Data...")
    scaler = joblib.load(f'{MODEL_DIR}scaler.joblib')
    imputer = joblib.load(f'{MODEL_DIR}imputer.joblib')
    pca = joblib.load(f'{MODEL_DIR}pca.joblib')
    model = joblib.load(f'{MODEL_DIR}ensemble_model.joblib')
    interpreter = joblib.load(f'{MODEL_DIR}shap_interpreter.joblib')
    feature_names = joblib.load(f'{MODEL_DIR}feature_names.joblib')
    explainer = shap.TreeExplainer(interpreter)
    
    # Load raw data for lookups (Keep it in memory for speed)
    raw_df = pd.read_csv(DATA_PATH)
    print("✅ System Ready.")
except Exception as e:
    print(f"❌ Error loading resources: {e}")

# --- NEW ENDPOINT: SERVE RESEARCH STATS ---
@app.get("/stats")
async def get_model_stats():
    """
    Returns the training metrics, confusion matrix, and runtime info.
    Reads from the JSON file generated by train.py.
    """
    try:
        with open(f'{MODEL_DIR}metrics.json', 'r') as f:
            data = json.load(f)
        return data
    except FileNotFoundError:
        return {"error": "Metrics not found. Run train.py first."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# --- EXISTING ENDPOINT: PREDICT BY ID ---
@app.get("/predict/{txn_id}")
async def predict_by_id(txn_id: int):
    """
    Simulate looking up a transaction by ID (Index in CSV).
    """
    try:
        # 1. Lookup Transaction
        if txn_id < 0 or txn_id >= len(raw_df):
            raise HTTPException(status_code=404, detail="Transaction ID not found in database.")
        
        # Get the specific row
        row = raw_df.iloc[[txn_id]]
        
        # 2. Filter & Align Features
        # We only want numeric columns that match our training features
        input_data = pd.DataFrame(columns=feature_names)
        
        # Map available columns from raw_df to input_data
        common_cols = list(set(feature_names) & set(row.columns))
        input_data.loc[0, common_cols] = row[common_cols].values[0]
        input_data = input_data.fillna(0) # Fill remaining with 0
        
        # 3. Preprocess
        data_imputed = imputer.transform(input_data)
        data_scaled = scaler.transform(data_imputed)
        
        # 4. Predict
        data_pca = pca.transform(data_scaled)
        prob = model.predict_proba(data_pca)[0][1]
        is_fraud = bool(prob > 0.5)
        
        # 5. Explain (SHAP)
        # Check if explainer expects a matrix or single instance
        shap_values = explainer.shap_values(data_scaled)
        
        # Handle SHAP output format (list for some classifiers, array for others)
        vals = shap_values[0] if isinstance(shap_values, list) else shap_values[0]
        
        # If shape mismatch occurs, ensure we are grabbing the first instance
        if len(vals.shape) > 1: 
             vals = vals[0] # Grab first row if it returns (1, features)

        feature_importance = list(zip(feature_names, vals))
        feature_importance.sort(key=lambda x: abs(x[1]), reverse=True)
        top_features = [{"feature": k, "impact": float(v)} for k, v in feature_importance[:5]]

        return {
            "transaction_id": txn_id,
            "fraud_probability": float(prob),
            "is_fraud": is_fraud,
            "explanation": top_features
        }

    except Exception as e:
        print(f"Prediction Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))